// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AcceptorClient is the client API for Acceptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcceptorClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareReply, error)
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptReply, error)
}

type acceptorClient struct {
	cc grpc.ClientConnInterface
}

func NewAcceptorClient(cc grpc.ClientConnInterface) AcceptorClient {
	return &acceptorClient{cc}
}

func (c *acceptorClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareReply, error) {
	out := new(PrepareReply)
	err := c.cc.Invoke(ctx, "/protoc.Acceptor/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acceptorClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptReply, error) {
	out := new(AcceptReply)
	err := c.cc.Invoke(ctx, "/protoc.Acceptor/Accept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcceptorServer is the server API for Acceptor service.
// All implementations must embed UnimplementedAcceptorServer
// for forward compatibility
type AcceptorServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareReply, error)
	Accept(context.Context, *AcceptRequest) (*AcceptReply, error)
	mustEmbedUnimplementedAcceptorServer()
}

// UnimplementedAcceptorServer must be embedded to have forward compatible implementations.
type UnimplementedAcceptorServer struct {
}

func (UnimplementedAcceptorServer) Prepare(context.Context, *PrepareRequest) (*PrepareReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedAcceptorServer) Accept(context.Context, *AcceptRequest) (*AcceptReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedAcceptorServer) mustEmbedUnimplementedAcceptorServer() {}

// UnsafeAcceptorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcceptorServer will
// result in compilation errors.
type UnsafeAcceptorServer interface {
	mustEmbedUnimplementedAcceptorServer()
}

func RegisterAcceptorServer(s grpc.ServiceRegistrar, srv AcceptorServer) {
	s.RegisterService(&Acceptor_ServiceDesc, srv)
}

func _Acceptor_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcceptorServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Acceptor/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcceptorServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acceptor_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcceptorServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Acceptor/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcceptorServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Acceptor_ServiceDesc is the grpc.ServiceDesc for Acceptor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Acceptor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.Acceptor",
	HandlerType: (*AcceptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Acceptor_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _Acceptor_Accept_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/paxos.proto",
}

// ProposerClient is the client API for Proposer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProposerClient interface {
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeReply, error)
}

type proposerClient struct {
	cc grpc.ClientConnInterface
}

func NewProposerClient(cc grpc.ClientConnInterface) ProposerClient {
	return &proposerClient{cc}
}

func (c *proposerClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeReply, error) {
	out := new(ProposeReply)
	err := c.cc.Invoke(ctx, "/protoc.Proposer/Propose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProposerServer is the server API for Proposer service.
// All implementations must embed UnimplementedProposerServer
// for forward compatibility
type ProposerServer interface {
	Propose(context.Context, *ProposeRequest) (*ProposeReply, error)
	mustEmbedUnimplementedProposerServer()
}

// UnimplementedProposerServer must be embedded to have forward compatible implementations.
type UnimplementedProposerServer struct {
}

func (UnimplementedProposerServer) Propose(context.Context, *ProposeRequest) (*ProposeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedProposerServer) mustEmbedUnimplementedProposerServer() {}

// UnsafeProposerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProposerServer will
// result in compilation errors.
type UnsafeProposerServer interface {
	mustEmbedUnimplementedProposerServer()
}

func RegisterProposerServer(s grpc.ServiceRegistrar, srv ProposerServer) {
	s.RegisterService(&Proposer_ServiceDesc, srv)
}

func _Proposer_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposerServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Proposer/Propose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposerServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Proposer_ServiceDesc is the grpc.ServiceDesc for Proposer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proposer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.Proposer",
	HandlerType: (*ProposerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _Proposer_Propose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/paxos.proto",
}

// LearnerClient is the client API for Learner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearnerClient interface {
	Learn(ctx context.Context, in *LearnRequest, opts ...grpc.CallOption) (*LearnReply, error)
}

type learnerClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnerClient(cc grpc.ClientConnInterface) LearnerClient {
	return &learnerClient{cc}
}

func (c *learnerClient) Learn(ctx context.Context, in *LearnRequest, opts ...grpc.CallOption) (*LearnReply, error) {
	out := new(LearnReply)
	err := c.cc.Invoke(ctx, "/protoc.Learner/Learn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearnerServer is the server API for Learner service.
// All implementations must embed UnimplementedLearnerServer
// for forward compatibility
type LearnerServer interface {
	Learn(context.Context, *LearnRequest) (*LearnReply, error)
	mustEmbedUnimplementedLearnerServer()
}

// UnimplementedLearnerServer must be embedded to have forward compatible implementations.
type UnimplementedLearnerServer struct {
}

func (UnimplementedLearnerServer) Learn(context.Context, *LearnRequest) (*LearnReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Learn not implemented")
}
func (UnimplementedLearnerServer) mustEmbedUnimplementedLearnerServer() {}

// UnsafeLearnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnerServer will
// result in compilation errors.
type UnsafeLearnerServer interface {
	mustEmbedUnimplementedLearnerServer()
}

func RegisterLearnerServer(s grpc.ServiceRegistrar, srv LearnerServer) {
	s.RegisterService(&Learner_ServiceDesc, srv)
}

func _Learner_Learn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LearnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnerServer).Learn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Learner/Learn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnerServer).Learn(ctx, req.(*LearnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Learner_ServiceDesc is the grpc.ServiceDesc for Learner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Learner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.Learner",
	HandlerType: (*LearnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Learn",
			Handler:    _Learner_Learn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/paxos.proto",
}
